# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "holaaaa"
    lane :android_beta_app do
        firebase_app_distribution(
            app: "1:570616457697:android:78aa823710311515618aa0",
            testers: "david962406@gmail.com, davidllanes962406@gmail.com",
            release_notes: "QA version",
            apk_path: "./app/build/outputs/apk/debug/app-debug.apk"
        )
    end
end



